scraper:
  base_url: "https://amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&category%5B%5D=business-intelligence&category%5B%5D=software-development&category%5B%5D=project-program-product-management-technical&category%5B%5D=machine-learning-science&category%5B%5D=data-science&category%5B%5D=operations-it-support-engineering&category%5B%5D=research-science&category%5B%5D=solutions-architect&country%5B%5D=LUX&distanceType=Mi&radius=24km&industry_experience=four_to_six_years&job_level%5B%5D=5&job_level%5B%5D=6&latitude=&longitude=&loc_group_id=&loc_query=&base_query=&city=&country=&region=&county=&query_options="
  max_workers: 3
  batch_size: 10
  delays:
    min: 1
    max: 3

output:
  data_dir: "data/raw"
  backup_dir: "data/backups"
  filename: "amazon_luxembourg_jobs.csv"

logging:
  level: "INFO"
  file: "logs/scraper.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 